### ISSUE TITLE
Extraction fails

### ISSUE THREAD

**Issue by mrx23dot** [ohmybahgosh/RockYou2021.txt#5]
I downloaded it from torrent, but can't extract according to instructions:

7za a rockyou2021.txt.7z.001
```
7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 

System ERROR:
E_NOTIMPL

```
rockyou2021.txt dictionary from kys234 on RaidForums$ ls
rockyou2021.txt.7z.001  rockyou2021.txt.7z.002

**Comment by lidarbtc** [comment]
Can you try download on anonfile or bayfile?

**Comment by ohmybahgosh** [comment]
Sorry, I'm not sure on this one...as I didn't create that torrent
